#!/usr/bin/env bash

cyan='\e[0;36m'
green='\e[0;34m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'
BlueF='\e[1;34m'

CIPHERMODE="aes-256-cbc"

function usage() {

    echo -e $cyan
    echo "usage: $0 -e -i test.txt -o test.txt.enc"
    echo "usage: $0 -e -i dir -o enc"
    echo "usage: $0 -e -p /path/to/pubkey -i test.txt -o test.txt.enc"
    echo "usage: $0 -e -p /path/to/pubkey -i dir -o .enc"
    echo "usage: $0 -d -i test.txt.enc -o test.txt"
    echo "usage: $0 -d -p /path/to/privatekey -i test.txt.enc -o test.txt"
    echo ""
}

function encrypt() {
    echo -e $okegreen
    echo "[+] ENCRYPT"
    echo "[+] INPUT:  "$INPUT_FILE
    echo "[+] OUTPUT: "$OUTPUT_FILE
    echo ""
    echo -e $red
    echo "[!] Your file will be encypted now!"
    echo ""
    if [[ $DEMODE -eq 1 ]]; then
        if [[ -f $INPUT_FILE ]]; then
            openssl rsautl -encrypt -inkey $KEYFILE -pubin -in $INPUT_FILE -out $OUTPUT_FILE
        elif [[ -d $INPUT_FILE ]]; then
            DIR=$INPUT_FILE/*
            for file in $DIR; do
                openssl rsautl -encrypt -inkey $KEYFILE -pubin -in $file -out $file.$OUTPUT_FILE
            done
        fi
    else
        if [[ -f $INPUT_FILE ]]; then
            openssl $CIPHERMODE -a -salt -in $INPUT_FILE -out $OUTPUT_FILE
        elif [[ -d $INPUT_FILE ]]; then
            DIR=$INPUT_FILE/*
            for file in $DIR; do
                openssl $CIPHERMODE -a -salt -in $file -out $file.$OUTPUT_FILE
            done
        fi
    fi
    echo -e $okegreen
    echo "[+] Done!"
}

function decrypt() {
    echo -e $okegreen
    echo "[+] DECRYPT"
    echo "[+] INPUT:  "$INPUT_FILE
    echo "[+] OUTPUT: "$OUTPUT_FILE
    if [[ $DEMODE -eq 1 ]]; then
        if [[ -f $INPUT_FILE ]]; then
            openssl rsautl -decrypt -inkey $KEYFILE -in $INPUT_FILE -out $OUTPUT_FILE
        elif [[ -d $INPUT_FILE ]]; then
            DIR=$INPUT_FILE/*
            for file in $DIR; do
                openssl rsautl -decrypt -inkey $KEYFILE -in $file -out $file.$OUTPUT_FILE
            done
        fi
    else
        if [[ -f $INPUT_FILE ]]; then
            openssl $CIPHERMODE -d -a -in $INPUT_FILE -out $OUTPUT_FILE
        elif [[ -d $INPUT_FILE ]]; then
            DIR=$INPUT_FILE/*
            for file in $DIR; do
                openssl $CIPHERMODE -d -a -in $file -out $file.$OUTPUT_FILE
            done
        fi
    fi
}



while getopts "tedi:o:p:Hh" opt;do
    case $opt in

    i)
        INPUT_FILE=$OPTARG
        if [[ -f $INPUT_FILE ]] ; then
			echo -e $okgreen
       		echo "[+] inputfile found!"
            echo ""
        elif [[ -d $INPUT_FILE ]] ; then
        	echo -e $okgreen
            echo "[+] directory found!"
            echo ""
			DIRMODE=1
        else
			echo -e $red
            echo "[!] INPUT NOT FOUND!"
            exit 1
            echo ""
        fi
        ;;
    e)
        MODE=1;;
	t)
		TARMODE=1;;
    d)
        MODE=2;;
    o)
        OUTPUT_FILE=$OPTARG;;
    p)
        KEYFILE=$OPTARG
        DEMODE=1
        if [[ ! -f $KEYFILE ]]; then
            echo -e $red
            echo "Keyfile not found"
            echo ""
            exit -1
        fi;;
        H|h)
                usage
        exit -1;;
        \?)
                usage
        exit -1;;
   esac
done

if [[ $MODE -eq 1 ]]; then
    encrypt
elif [[ $MODE -eq 2 ]]; then
    decrypt
else
    echo -e $red "FAILURE"
fi
